version: '3.8'

services:
  backend:
    container_name: backend-container
    restart: always
    build:
      context: ./backend/container
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./backend/container/src:/app/dev/src
      - ./backend/container/tsconfig.json:/app/dev/tsconfig.json
      - ./backend/container/.env:/app/dev/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
  # volumes:
  #   exclude:
  # volumes:
  #   - ./backend/container:/app
  #   - /app/node_modules
  # environment:
  #   - NODE_ENV=development
  #   - PORT=3000
  #   - DATABASE_URL=${DATABASE_URL:-mongodb://localhost:27017/dev}
  #   - JWT_SECRET=${JWT_SECRET:-dev_secret}
  #   - CORS_ORIGIN=*
  # command: npm run dev
  # healthcheck:
  #   test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
  #   interval: 30s
  #   timeout: 10s
  #   retries: 3
